[package]
name = "seq"
version = "0.1.5"
authors = ["Robert Bakaric <rbakaric@exaltum.eu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
snafu = "*"
fxhash = "*"
num_cpus = "1.13.0"
fs2 = "0.4.3"
sys-info = "*"
